#!/bin/sh

#.husky/test-api
#.husky/test-app

while read local_ref local_sha remote_ref remote_sha
do
  case "$local_ref" in refs/tags/*)
    latest_commit=$(git rev-parse main)

    tag_commit=$(git rev-parse "$local_sha")

    if [ "$latest_commit" != "$tag_commit" ]; then
      echo "Error: You can only tag the latest commit on the main branch."
      exit 1
    fi
    ;;
  esac
done
