name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout repository
        uses: actions/checkout@v4
      - run: echo "Tag push"
      - run: git tag
