name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  publish-app:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout repository
        uses: actions/checkout@v4
      - name: Determine branch from tag
        run: |
          tag_commit=$(git rev-parse ${GITHUB_REF#refs/tags/})
          branches=$(git branch --contains $tag_commit)
          echo $branches | grep -q "main" > /dev/null 2>&1
          if [[ $? -ne 0 ]]; then
            echo "The last commit from the tag does not belong to main branch."
            exit 1
          fi
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login Docker to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ secrets.AWS_REGISTRY }}
      - name: Build and publish docker image for epicstory-app
        run: |
          cd deploy
          ./publish.sh app ${GITHUB_REF#refs/tags/v} ${{ secrets.AWS_REGION }}
  publish-api:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout repository
        uses: actions/checkout@v4
      - name: Determine branch from tag
        run: |
          tag_commit=$(git rev-parse ${GITHUB_REF#refs/tags/})
          branches=$(git branch --contains $tag_commit)
          echo $branches | grep -q "main" > /dev/null 2>&1
          if [[ $? -ne 0 ]]; then
            echo "The last commit from the tag does not belong to main branch."
            exit 1
          fi
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login Docker to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ secrets.AWS_REGISTRY }}
      - name: Build and publish docker image for epicstory-api
        run: |
          cd deploy
          ./publish.sh api ${GITHUB_REF#refs/tags/v} ${{ secrets.AWS_REGION }}
